#!/usr/bin/env python3
"""Generate assets/editor-doc-snippets.js: real docstrings for a curated set
of names the authoring editor's code blocks might show a hover tooltip for.

Why this exists at all: the editor (assets/editor.js) never boots Pyodide —
see ARCHITECTURE.md §3 — so unlike a student's cell (which reads a real
`inspect.getdoc()` off a real running object, assets/tutorial-runtime.js's
`docFor`), the editor has no live interpreter to ask. Rather than hand-write
documentation that can drift from what the packages actually say, this
script asks the same real Pyodide the rest of the site uses, once, and
commits the answer — a captured fact, not an invented one.

NAMES below is deliberately not "every function in numpy/pandas/matplotlib"
— it is grep-derived from what the curriculum actually calls
(`grep -rhoE '\\.[A-Za-z_]+\\(' tutorials/ setup/ | sort | uniq -c | sort -rn`,
cross-checked against the exact `plt.`, `pd.`, `math.`, `random.` prefixed
calls). `numpy` is not in the list below because nothing in tutorials/ or
setup/ currently calls it as `np.anything` — it would be pure guessing, not
a captured fact, to include it. Only genuinely callable names are listed;
`math.pi`, a constant, has no useful docstring and is left out.

Needs a self-hosted Pyodide (`python3 dev/fetch_pyodide.py`) and Playwright
with a Chromium (`pip install playwright && playwright install chromium`).

    python3 dev/generate_doc_snippets.py
"""

from __future__ import annotations

import functools
import http.server
import json
import socketserver
import threading
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PYODIDE = ROOT / "dev" / "pyodide"
OUT = ROOT / "assets" / "editor-doc-snippets.js"

NAMES = {
    "plt": [
        "Circle", "axhline", "axvline", "bar", "figure", "gca", "grid",
        "hist", "legend", "plot", "scatter", "show", "subplots",
        "tight_layout", "title", "xlabel", "ylabel",
    ],
    "pd": ["DataFrame"],
    "math": [
        "acos", "asin", "atan", "atan2", "comb", "cos", "degrees",
        "factorial", "hypot", "log2", "log10", "perm", "radians", "sin",
        "sqrt", "tan",
    ],
    "random": [
        "choice", "choices", "randint", "randrange", "random", "sample",
        "seed", "shuffle", "uniform",
    ],
}


def _summary(doc: str | None) -> str | None:
    """A hover tooltip is a line or two, not matplotlib's full parameter
    reference — the first paragraph, real text lifted verbatim from the real
    docstring rather than rewritten, just the part short enough to fit."""
    if not doc:
        return doc
    return doc.split("\n\n", 1)[0].replace("\n", " ").strip()


def main() -> None:
    """The command-line entry point. Spins up a tiny local web server
    serving the self-hosted Pyodide files (`_QuietHandler` below, on a
    randomly assigned free port — `("127.0.0.1", 0)`'s `0` port asks the
    OS to pick one), uses a real headless browser to boot Pyodide and
    read the real docstrings off it (`_collect`), then writes the result
    out as a small generated JavaScript file the authoring editor can
    load directly, with no Pyodide of its own needed.
    """
    if not (PYODIDE / "pyodide.mjs").exists():
        raise SystemExit("no self-hosted Pyodide — run `python3 dev/fetch_pyodide.py` first")

    handler = functools.partial(_QuietHandler, directory=str(PYODIDE))
    with socketserver.TCPServer(("127.0.0.1", 0), handler) as server:
        port = server.server_address[1]
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        try:
            snippets = _collect(f"http://127.0.0.1:{port}")
        finally:
            server.shutdown()
            thread.join(timeout=5)

    snippets = {
        module: {name: _summary(doc) for name, doc in entries.items()}
        for module, entries in snippets.items()
    }

    total = sum(len(v) for v in snippets.values())
    header = (
        "/* Generated by dev/generate_doc_snippets.py — do not hand-edit.\n"
        " * Real docstrings, captured once from a real Pyodide interpreter, for\n"
        " * the authoring editor's hover tooltip (vendor-src/milkdown-entry.js),\n"
        " * which has no live interpreter of its own to ask. See that script's\n"
        " * own docstring for what NAMES is grep-derived from and why numpy is\n"
        " * not here. Re-run it if the curated name list changes or the pinned\n"
        " * Pyodide version does. */\n"
    )
    body = "export const docSnippets = " + json.dumps(snippets, indent=2, ensure_ascii=False) + ";\n"
    OUT.write_text(header + body)
    print(f"wrote {OUT.relative_to(ROOT)}: {total} docstrings across {len(snippets)} modules")


def _chromium_path() -> str | None:
    """Looks for a pre-installed Chromium browser in the well-known path
    this project's own dev/CI environment uses, so `_collect()` below can
    reuse it directly instead of triggering Playwright's own (slow,
    network-dependent) browser download. Returns `None` when there isn't
    one there, in which case Playwright falls back to its own default
    behaviour.
    """
    root = Path("/opt/pw-browsers")
    if not root.exists():
        return None
    for chrome in sorted(root.glob("chromium-*/chrome-linux/chrome")):
        return str(chrome)
    return None


def _collect(base_url: str) -> dict[str, dict[str, str]]:
    """Does the actual work of asking a real Pyodide for real docstrings:
    opens a headless browser tab pointed at the local server serving the
    Pyodide files, then runs JavaScript in that page (via
    `page.evaluate`) that boots Pyodide, imports the modules NAMES cares
    about, and asks Python's own `inspect.getdoc()` for each requested
    name's docstring — the exact same function
    `assets/tutorial-runtime.js`'s own `docFor` uses for a student's live
    hover tooltips, just run once here at build time instead of live in a
    student's browser. The big triple-quoted string passed to
    `page.evaluate` is real JavaScript, which itself contains a
    triple-backtick Python string passed to `pyodide.runPython(...)` —
    worth reading slowly, since it's genuinely three languages nested
    inside each other (Python calling into JavaScript calling into
    Python).
    """
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        launch = {"args": ["--no-sandbox"]}
        candidate = _chromium_path()
        if candidate:
            launch["executable_path"] = candidate
        browser = p.chromium.launch(**launch)
        page = browser.new_page()
        # Any same-origin document works — content is irrelevant, this only
        # needs a real origin for the dynamic import() below to resolve
        # against. Python's directory-listing page is good enough.
        page.goto(base_url)
        result = page.evaluate(
            """async ({names}) => {
                 const { loadPyodide } = await import("./pyodide.mjs");
                 const pyodide = await loadPyodide({ indexURL: "./" });
                 await pyodide.loadPackage(["pandas", "matplotlib"]);
                 pyodide.runPython(`
import inspect, json, math, random
import matplotlib.pyplot as plt
import pandas as pd
_modules = {"plt": plt, "pd": pd, "math": math, "random": random}
`);
                 const namesJson = pyodide.toPy(names);
                 pyodide.globals.set("_names", namesJson);
                 const resultJson = pyodide.runPython(`
json.dumps({
    mod: {
        name: inspect.getdoc(getattr(_modules[mod], name))
        for name in wanted
    }
    for mod, wanted in _names.items()
})
`);
                 namesJson.destroy();
                 return JSON.parse(resultJson);
               }""",
            {"names": NAMES},
        )
        browser.close()
        return result


class _QuietHandler(http.server.SimpleHTTPRequestHandler):
    """A plain file-serving HTTP handler with logging silenced.
    `log_message` is a hook the base class calls for every request to
    print an access-log line; overriding it to do nothing keeps this
    script's own output limited to what it actually chooses to print,
    instead of being interleaved with a stream of GET-request logs for
    every Pyodide file the browser fetches."""

    def log_message(self, *args):
        pass


if __name__ == "__main__":
    main()
